services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spark-net
      
  producer:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: producer
    depends_on:
      - kafka
    command: bash -c "/app/utils/wait-for-it.sh kafka:9092 -- sleep 3 && python3 /app/kafka/topics.py && python3 /app/kafka/producer.py"
    volumes:
      - ./kafka:/app/kafka
      - ./data:/app/data
      - ./utils:/app/utils
    networks:
      - spark-net

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: consumer
    depends_on:
      - kafka
    command: bash -c "spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0 /app/spark/stream_consumer.py"
    volumes:
      - ./spark:/app/spark
      - ./data:/app/data
    networks:
      - spark-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - spark-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - spark-net

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - spark-net
    volumes:
      - ./spark:/app/spark
      - ./data:/app/data
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master"

  spark-worker-1:
    image: apache/spark:3.5.0
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - spark-net
    volumes:
      - ./spark:/app/spark
      - ./data:/app/data
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"

  spark-worker-2:
    image: apache/spark:3.5.0
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    networks:
      - spark-net
    volumes:
      - ./spark:/app/spark
      - ./data:/app/data
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"

  airflow:
    user: "50000:0"
    image: apache/airflow:2.8.1
    container_name: airflow
    depends_on:
      - kafka
      - spark-master
      - postgres
    environment:
      - AIRFLOW_HOME=/app/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.www.security.DefaultAuthBackend
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/tmp/airflow_logs
      - AIRFLOW__CORE__XCOM_BACKEND=airflow.models.xcom.BaseXCom
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./airflow:/app/airflow
      - ./spark:/app/spark
      - ./data:/app/data
      - ./utils:/app/utils
    ports:
      - "8088:8080"
    command: bash -c "/app/utils/wait-for-it.sh postgres:5432 -- mkdir -p /tmp/airflow_logs && airflow db migrate && airflow connections create-default-connections && airflow scheduler & airflow webserver"
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
volumes:
  postgres_data: